---
- name: Deploy Task Management API
  hosts: all
  become: yes
  vars:
    repo_url: "https://github.com/tharundv/Task-Management.git"
    app_dir: "{{ playbook_dir }}"  # Use the current directory where the playbook is located
    node_version: "20.x"  # Use '20.x' to install the latest version in the 20.x series

  tasks:
    - name: Install required packages
      apt:
        name: 
          - curl
          - software-properties-common
          - gnupg2  # Required for adding repositories securely
        state: present
        update_cache: yes

    - name: Add NodeSource APT repository
      shell: curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
      args:
        executable: /bin/bash

    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB service
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        update: yes

    - name: Install npm dependencies
      npm:
        path: "{{ app_dir }}"
        state: present

    - name: Start the application
      command: npm start
      args:
        chdir: "{{ app_dir }}"
      async: 10
      poll: 0

    - name: Wait for the application to start
      wait_for:
        port: 4000
        delay: 5
        timeout: 30
